services:
    postgres:
        container_name: postgres
        image: docker.io/library/postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: api
            POSTGRES_PASSWORD: N6QmF7kSNGLq
            POSTGRES_DB: wattbudget
        volumes:
            - postgres_data:/var/lib/postgresql
        networks:
            - wattbudget-network
    nest-api:
        build: ./api
        container_name: nest-api
        restart: always
        env_file:
            - ./api/.env
        ports:
            - "5000:5000"
        volumes:
            - ./api:/usr/src/nest-api
        command: npm run start:dev
        depends_on:
            - postgres
        networks:
            - wattbudget-network

volumes:
    postgres_data:
        driver: local

networks:
    wattbudget-network:
        driver: bridge
