services:
    postgres:
        container_name: postgres
        image: docker.io/library/postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: api
            POSTGRES_PASSWORD: N6QmF7kSNGLq
            POSTGRES_DB: wattbudget
        volumes:
            - postgres_data:/var/lib/postgresql
        networks:
            - wattbudget-network
    nest-api:
        build: ./api
        container_name: nest-api
        restart: always
        env_file:
            - ./api/.env
        ports:
            - "5000:5000"
        volumes:
            - ./api:/usr/src/nest-api
        command: npm run start:dev
        depends_on:
            - postgres
        networks:
            - wattbudget-network

    front:
        container_name: front
        build: ./FRONT
        image: front
        depends_on:
            - nest-api
        volumes:
            - ./FRONT:/usr/src/app
            - astro_node_modules:/app/node_modules
        ports:
            - 4321:4321
        environment:
            - PUBLIC_API_URL=http://localhost:5000
        networks:
            - wattbudget-network

volumes:
    postgres_data:
        driver: local
    astro_node_modules:

networks:
    wattbudget-network:
        driver: bridge
