-- AlterTable
ALTER TABLE "recharge" ALTER COLUMN "fullHour" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "offPeakHour" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "totalCost" SET DATA TYPE DOUBLE PRECISION;
